sudo: false

language: c

addons:
    apt:
        packages:
            - fonts-lmodern
            - texlive-latex-recommended
            - texlive-latex-extra
            - texlive-xetex
            - texlive-fonts-recommended
            - texlive-fonts-extra
            - latex-xcolor

script:
    - make

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
        cd $TRAVIS_BUILD_DIR
        git checkout --orphan gh-pages
        git rm -rf .
        mkdir pdf
        mv cv.pdf pdf/cv.pdf
        git add -f pdf/cv.pdf
        touch .nojekyll
        git -c user.name='travis' -c user.email='travis' commit -m "current pdf"
        git push -q -f https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG gh-pages
    fi
