name: Build Latex CV
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 1"  # every day at 1 AM Eastern
jobs:
  build_latex:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - run: pythom -m pip install -r requirements.txt

      - name: Install modern fonts
        run: sudo apt-get install fonts-lmodern

      - name: Install tex
        uses: xu-cheng/texlive-action/full@v1

      - run: apk add make

      - name: Compile LaTeX document
        with:
          run: |
            python get_pubs.py
            make getpubs
            make pubstex
            make

      - name: Rearrange files
        run: |
          rm .gitignore
          touch .nojekyll
          mkdir pdf
          mv *.pdf pdf/

      - name: Deploy PDF
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./pdf
          force_orphan: true
