name: Build Latex CV
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 1"  # every Monday at 1 AM Eastern
jobs:
  build_latex:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - run: python -m pip install -r requirements.txt

      - name: Install modern fonts
        run: sudo apt-get install fonts-lmodern build-essential

      - name: Retrieve updated publications list
        run: |
          make getpubs
          make pubstex
        env:
          ADS_DEV_KEY: ${{ secrets.ADS_DEV_KEY }}

      - name: Compile latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            PriceWhelan-cv.tex
            PriceWhelan-pubs.tex
          latexmk_use_xelatex: true

      - name: Rearrange files
        run: |
          rm .gitignore
          touch .nojekyll
          mkdir pdf
          mv *.pdf pdf/

      - name: Deploy PDF
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./pdf
          force_orphan: true
